### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by AndresFMoya**

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi Team, nice effort so far the test is passing, this is just to point out good practice with testing and making sure you guys stay used to it.

specs should cover positive and negative scenarios where possible
Example: “it creates an object if all required attributes are passed” and “it does not create object if required attributes are missing”.
Please do the corrections and request for a re-review :pray:

**Comment by AndresFMoya** [comment]
Hi @Oghenebrume50. Thanks for your feedback. We add tests to negative scenarios and request for a re-review. Regards.

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — APPROVED** [review]
### Hi there team :hand: 
Nicely done, you covered all the necessary cases and all tests are passing. :clap: :tada: 
### I'm approving this PR :+1: 
Go on and merge it.
Happy coding :computer:

**Pull request merged**
